# Staging: promotion från DEV, samma image (staging-<sha>)
image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: ""
  digest: "sha256:ec8e18ae929f388ddd95e9a20b0371fb3533e0b00603eb56ab212a55d2415386"
  requests: { cpu: 75m, memory: 192Mi }
  limits:   { cpu: 300m, memory: 384Mi }

# TODO: Slå på när du Prometheus Operator redo i klustret
serviceMonitor:
  enabled: true
 