{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "electricity.fullname" . }}-ingress
  labels:
    app.kubernetes.io/name: electricity-price
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: electricity-price
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
{{- end }}
