{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "electricity.fullname" . }}
  labels:
    app.kubernetes.io/name: electricity-price
    {{- /* Svenska: extra etiketter för att matcha Prometheus' selector (t.ex. release: kube-prometheus-stack) */}}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: electricity-price
  endpoints:
    - port: {{ .Values.serviceMonitor.portName }}   # Måste matcha Service-portens namn
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- with .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}                        
      {{- end }}
{{- end }}
