image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: v1.3.0
  digest: "sha256:b65d9d6e948c25f26011f40f64d115b8ac1a2db2f61122998c93a60667e97861"
resources:
  requests: { cpu: 300m, memory: 512Mi }
  limits:   { cpu: 600m, memory: 1Gi }
  
ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: prod.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls: 
    enabled: true
    secretName: electricity-price-prod-tls

networkPolicy:
  enabled: true

serviceMonitor:
  enabled: true

alerts:
  enabled: true
  env: prod
  targetNamespace: electricity-prod

  latencyP95Seconds: 0.5
  cpuCoresThreshold: 0.45
  memoryThresholdMi: 800

