image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: v1.0.6
  digest: "sha256:e9d6d57a393fa6435e3eee1ab6af7501ef322b6769193c5869d4d4155642e6bf"
resources:
  requests: { cpu: 300m, memory: 512Mi }
  limits:   { cpu: 600m, memory: 1Gi }
  
ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: prod.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls: 
    enabled: true
    secretName: electricity-price-prod-tls

networkPolicy:
  enabled: true

serviceMonitor:
  enabled: true

alerts:
  enabled: true
  env: prod
  targetNamespace: electricity-prod

  latencyP95Seconds: 0.5
  cpuCoresThreshold: 0.45
  memoryThresholdMi: 800

