image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: v1.3.2
  digest: "sha256:fede9b2e2ee6e776dd1c530b1c574bff3aad2deda9c1256bddb41ea507d14df3"
resources:
  requests: { cpu: 300m, memory: 512Mi }
  limits:   { cpu: 600m, memory: 1Gi }
  
ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: prod.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls: 
    enabled: true
    secretName: electricity-price-prod-tls

networkPolicy:
  enabled: true

serviceMonitor:
  enabled: true

alerts:
  enabled: true
  env: prod
  targetNamespace: electricity-prod

  latencyP95Seconds: 0.5
  cpuCoresThreshold: 0.45
  memoryThresholdMi: 800

