---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: electricity-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/igor88gomes/electricity-price-gitops.git
    targetRevision: main
    path: base
    helm:
      valueFiles:
        - ../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: electricity-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
