image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: dev-2bc99ed
  digest: "sha256:61e51728e8b28db96d041149596f0aa7d225112a87c1ad2bb3a435b5c3ad4ca4"

probes:
  startup:
    enabled: true

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: dev.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true          
    secretName: electricity-price-dev-tls 

networkPolicy:
  enabled: true

serviceMonitor:
  enabled: false

alerts:
  enabled: false


