image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: dev-82084e7
  digest: "sha256:c7cef95dae89c4c7bfbdef433a8c9bf9e93ad1014467a92f91014ae3e2d8a9ea"

probes:
  startup:
    enabled: true

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: dev.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true          
    secretName: electricity-price-dev-tls 

networkPolicy:
  enabled: true

serviceMonitor:
  enabled: false

alerts:
  enabled: false


