image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: dev-3501fbe
  digest: "sha256:a1a5e52c4202f8a91f2a3083525a116b359166bc53725f11f85bde577da6aa07"

probes:
  startup:
    enabled: true

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: dev.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true          
    secretName: electricity-price-dev-tls 

networkPolicy:
  enabled: true

serviceMonitor:
  enabled: false

alerts:
  enabled: false


